PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX salt: <http://slobr.linkedmusic.org/salt/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT ?uri ?appelenlabel (strbefore(strafter(?period,"="), ";") AS ?start) (strbefore(strafter(strafter(?period,";"), "="), ";") AS ?end) WHERE  {{
    {0}
    ?uri salt:in_saltset <http://slobr.linkedmusic.org/saltsets/chgis_places> .
    ?uri rdfs:label ?appelenlabel .
    OPTIONAL {{
      ?uri dcterm:temporal ?period .
    }}
}}

