PREFIX dc: <http://purl.org/dc/terms/>
PREFIX mo: <http://purl.org/ontology/mo/>
select ?uri ?works ?role ?musicbrainz where  {{ 
    {0}
    ?uri dc:contributor ?workuri ; 
        <http://127.0.0.1:3000/contributorRole> ?role ;
        mo:musicbrainz_guid ?musicbrainz.
    ?workuri dc:title ?works.
}}
