PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?uri ?works ?role ?musicbrainz where  {{ 
    {0}
    ?uri dc:identifier ?workuri ; 
        <http://127.0.0.1:3000/contributorRole> ?role ;
        <http://127.0.0.1:3000/musicbrainz_gid> ?musicbrainz.
    ?workuri dc:title ?works.
}}
