SELECT DISTINCT ?uri ?label
WHERE { 
    GRAPH <http://eeboo.oerc.ox.ac.uk/EMS> {
        ?uri rdfs:label ?label ;
           <http://eeboo.oerc.ox.ac.uk/salt/in_salt_set> <http://eeboo.oerc.ox.ac.uk/saltsets/ems_composers>
    }
}
