PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX etree: <http://etree.linkedmusic.org/vocab/>
PREFIX event: <http://purl.org/NET/c4dm/event.owl#>
select distinct ?uri ?tags ?performedAt where {{ 
   {0}
   GRAPH <http://etree.linkedmusic.org/data/graphs/artists> {{ 
        ?uri salt:in_saltset saltset:etree_artists 
    }}
    
    ?uri etree:mbTag ?tags ;
        mo:performed ?perf .
    ?perf event:place ?perfplace .
    ?perfplace etree:location ?perfloc;
        etree:name ?venue .
    BIND(CONCAT(?perfloc, ": ", ?venue) as ?performedAt .
}}
