PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX dct: <http://purl.org/dc/terms/>
INSERT {
    GRAPH <http://127.0.0.1:8890/slickmem_item_creators> { 
        ?workuri frbr:creator ?creatoruri .
        ?creatoruri rdfs:label ?creatorname .
        ?creatoruri <http://127.0.0.1:8890/salt/in_salt_set> <http://127.0.0.1:8890/saltsets/slickmem_item_creators> .
    }
}
WHERE { 
 ?workuri a mo:MusicalWork ;
          dct:title ?worktitle;
          frbr:creator ?creatorname .
          BIND(IRI(CONCAT(STR(?workuri), "_creator")) as ?creatoruri) .
}

