INSERT {
    GRAPH <http://127.0.0.1:8890/EMS> { 
        ?uri <http://127.0.0.1:8890/salt/in_salt_set> <http://127.0.0.1:8890/saltsets/ems_composers> .
    }
}
WHERE { 
    GRAPH <http://127.0.0.1:8890/EMS> {
        ?uri <http://127.0.0.1:3000/contributorRole> "Composer" ;
           <http://purl.org/dc/elements/1.1/contributor> ?label .
    }
}
