PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX slobr: <http://eeboo.oerc.ox.ac.uk/slobr/>
PREFIX slickmem: <http://eeboo.oerc.ox.ac.uk/slickmem/>
PREFIX ems: <http://eeboo.oerc.ox.ac.uk/EMS>
INSERT {
    GRAPH <http://eeboo.oerc.ox.ac.uk/EMS> { 
        ?uri a ems:Composer ; 
             rdfs:label ?label ;
        <http://eeboo.oerc.ox.ac.uk/salt/in_salt_set> <http://eeboo.oerc.ox.ac.uk/saltsets/ems_composers> ;
             <http://eeboo.oerc.ox.ac.uk/slobr/ems/linkedbrainz_uri> ?linkedbrainz_uri .
    }
}
WHERE { 
    GRAPH <http://eeboo.oerc.ox.ac.uk/EMS> {
        ?uri <http://eeboo.oerc.ox.ac.uk/slobr/ems/contributorRole> "Composer" ;
           rdfs:label ?label ;
           mo:musicbrainz_guid ?mbz_uri .
        BIND(IRI(CONCAT(STR(?mbz_uri), "#_")) as ?linkedbrainz_uri) .
    }
}
