PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX dct: <http://purl.org/dc/terms/>
select distinct ?uri ?artist ?releaseTitle ?trackTitle where {{ 
    {0}
    graph <http://linkedbrainz.org> {{ 
        ?uri a mo:MusicArtist  ; 
             foaf:name ?artist .
        ?release a mo:Release ;
               dct:title ?releaseTitle ;
               foaf:maker ?uri.
        ?track a mo:Track ;
             dct:title ?trackTitle ;
             foaf:maker ?uri.
    }}
}}
