PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX salt: <http://slobr.linkedmusic.org/salt/>
PREFIX saltset: <http://slobr.linkedmusic.org/saltsets/>

SELECT DISTINCT ?uri ?label 
WHERE { 
   GRAPH <http://linkedbrainz.org> { 
        ?uri salt:in_saltset saltset:lbz_artist ; 
             rdfs:label ?label .
   }
}
LIMIT 10000
