PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX sim: <http://purl.org/ontology/similarity/>
SELECT distinct ?uri ?outside_uri ?books
WHERE {{
    {0} 
    OPTIONAL {{
    ?slickmem_alignment sim:Subject ?uri ;
        sim:Object ?outside_uri .
    }} .
    OPTIONAL {{
        ?b foaf:maker ?uri ;
           rdfs:label ?books .
    }}
}}
