PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX dct: <http://purl.org/dc/terms/>
SELECT distinct ?uri ?works ?in_books ?book_maker ?book_maker_uri
WHERE {{
    {0}
    ?workuri <http://purl.org/vocab/frbr/core#creator> ?uri ;
           rdfs:label ?works .
           ?workuri dct:isPartOf ?source .
    ?source rdfs:label ?in_books .
    OPTIONAL {{  #source might not have a maker...
        ?source foaf:maker ?book_maker_uri.
        ?book_maker_uri rdfs:label ?book_maker.
    }} .
    FILTER isIRI(?uri) .
}}
