SELECT DISTINCT ?uri ?label
WHERE { 
    GRAPH <http://eeboo.oerc.ox.ac.uk/slickmem> {
        ?uri rdfs:label ?label ;
            <http://eeboo.oerc.ox.ac.uk/salt/in_salt_set> <http://eeboo.oerc.ox.ac.uk/saltsets/slickmem_persons> .
        ?outside_uri <http://purl.org/ontology/similarity/Subject> ?uri ;
                     <http://purl.org/ontology/similarity/distance> ?distance .  
        FILTER(?distance = "None0None") . #excludes slickmem automated searches 

    }
}

